image: node:latest

stages:
- install
- build
- test
- deploy

install:
  stage: install
  only:
  - master
  script:
  - npm install
  cache:
    paths:
    - node_modules/
    - .awcache/

build:
  stage: build
  dependencies: 
  - install
  only:
  - master
  script:
  - npm run build:all
  artifacts:
    paths:
    - build/

test:
  stage: test
  dependencies: 
  - install
  - build
  only:
  - master
  script:
  - npm run test

deploy:
  stage: deploy
  dependencies: 
  - install
  - test
  - build
  only:
  - master
  script:
  - echo sike, no deployment
  
