image: node:latest

stages:
- install
- build
- test
- deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
  - .awcache/

install:
  stage: install
  only:
  - master
  script:
  - npm install

build:
  stage: build
  dependencies: 
  - install
  only:
  - master
  script:
  - npm run all
  artifacts:
    paths:
    - build/

test:
  stage: test
  dependencies: 
  - install
  - build
  only:
  - master
  script:
  - npm run test

deploy:
  stage: deploy
  dependencies: 
  - install
  - test
  - build
  only:
  - master
  script:
  - echo sike, no deployment
  
