image: charlieharutaka/cetacea:latest

stages:
- install
- build
- test
- deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
  - .awcache/

install:
  stage: install
  only:
  - master
  script:
  - npm install

build:
  stage: build
  dependencies: 
  - install
  only:
  - master
  script:
  - npm run build
  artifacts:
    paths:
    - build/

build-grammar:
  stage: build
  dependencies:
  - install
  only:
  - master
  script:
  - npm run build:antlr
  artifacts:
    paths:
    - antlr_config/antlr/

test:
  stage: test
  dependencies:
  - install
  - build
  - build-grammar
  only:
  - master
  script:
  - cd antlr_config/antlr && ls && cd ../..
  - npm run test

lint:
  stage: test
  dependencies: 
  - install
  - build
  only:
  - master
  script:
  - npm run lint

deploy:
  stage: deploy
  dependencies: 
  - install
  - test
  - build
  only:
  - master
  script:
  - echo sike, no deployment
  
