#!/bin/sh

LEXER_FILE=WJSCLexer.g4
PARSER_FILE=WJSCParser.g4

BASEDIR=$(dirname $0)

TARGET_DIR=./antlr

rm -rf $TARGET_DIR

echo Compiling the lexer..
java -jar $BASEDIR/../lib/antlr-4.7-complete.jar $BASEDIR/$LEXER_FILE -o $TARGET_DIR antlr -no-listener -visitor -Werror 

if [ $? -ne 0 ]
then 
	exit 1
fi

echo Compiling the parser..
java -jar $BASEDIR/../lib/antlr-4.7-complete.jar $BASEDIR/$LEXER_FILE $BASEDIR/$PARSER_FILE -o $TARGET_DIR antlr -no-listener -visitor -Werror
